Add track changes support to audit log
getodk/xforms-spec pull request #231
Opened 2019-05-20 17:53 UTC by yanokwa

2019-05-20 19:39 UTC, MartijnR requested changes
If this this attribute is not required, would be good to mention that.

Also, in that case, good to mention the default value.

2019-05-20 21:47 UTC, lognaturel commented
Agreed with @MartijnR's requests. The naming and namespace seem consistent to me so no concerns there.

To be fully explicit for posterity, my understanding of how booleans work in XPath is that the absence of the attribute or the attribute set to value `""` would mean the attribute has boolean false but any other value given to the attribute would mean boolean true. That is, in addition to `odk:track-changes="true"`, `odk:track-changes="false"` would turn on change tracking, as would `odk:track-changes="0"`.

Here, @yanokwa is proposing to continue a convention established [here](https://opendatakit.github.io/xforms-spec/#submission-attributes) with `orx:auto-send` and `orx:auto-delete` to consider `"true"` as boolean true and anything else as false. This is more intuitive so I'm in support of it.

Somewhat annoyingly, this deviates from [`boolean-from-string`](https://opendatakit.github.io/xforms-spec/#fn:boolean-from-string) which, in addition to `"true"`, considers `"1"` as boolean true.

2019-05-20 21:52 UTC, lognaturel approved these changes

2019-05-21 16:19 UTC, MartijnR commented
Thanks. I actually missed the question about booleans. I see this as a string value that happens to look a little like a boolean because of the values we accept.  Here are a few more: https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/xfdl_r_xforms_submission.html

I thought an actual boolean attribute would basically be presence (true) or absence (false) of the attribute regardless of any value (in HTML the value can be either "" or the name of the attribute). In this case because there was precedent in XForms/XPath for such a non-evaluated on/off options (`indent`, `omit-xml-declaration`), we chose the same `"true"`, `"false"` string values (for e.g. auto-send). I agree that it makes most sense to consider any other value as irrelevant and therefore use the default.

2019-05-21 16:20 UTC, MartijnR approved these changes

2019-05-21 16:20 UTC, MartijnR commented
Thanks. I actually missed the question about booleans. I see this as a string value that happens to look a little like a boolean because of the values we accept.  Here are a few more: https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/xfdl_r_xforms_submission.html

I thought an actual boolean attribute would basically be presence (true) or absence (false) of the attribute regardless of any value (in HTML the value can be either "" or the name of the attribute). In this case because there was precedent in XForms/XPath for such a non-evaluated on/off options (`indent`, `omit-xml-declaration`), we chose the same `"true"`, `"false"` string values (for e.g. auto-send). I agree that it makes most sense to consider any other value as irrelevant and therefore use the default.

2019-05-21 16:20 UTC, merged

2019-05-21 16:52 UTC, lognaturel commented
Oh good, I'm so happy there's a precedent! Your explanation is perfect.

I'm not sure where I got the < 0 part in my prior comment but 0 or `NaN` being false seems consistent with the [XPath 1](https://www.w3.org/TR/1999/REC-xpath-19991116/#function-boolean) spec. Regardless, I think expecting "true" and considering everything else the default "false" is much easier to explain.