Update README.md
getodk/xforms-spec pull request #268
Opened 2020-04-18 16:33 UTC by MartijnR

2020-04-18 19:36 UTC, lognaturel requested changes

2020-04-18 19:36 UTC, lognaturel commented on README.md
> +Published at [https://getodk.github.io/xforms-spec/](https://opendatakit.github.io/xforms-spec/)
Actual link needs to change too!

2020-04-18 20:26 UTC, MartijnR commented
OMG, am glad you're checking!

2020-04-19 14:10 UTC, lognaturel approved these changes
That’s more like it! 😊

2020-04-19 23:44 UTC, merged