Add entities sub-spec
getodk/xforms-spec pull request #299
Opened 2022-11-10 23:08 UTC by lognaturel

The entities sub-spec defines an initial set of concepts in support of [entity-based data collection](https://forum.getodk.org/t/entity-based-data-collection/38115).

The ODK core team and TAB members have been iterating on the spec and its XLSForm companion in [this document](https://docs.google.com/document/d/1-O_wT0JZZFaWvzHl_krrzERJcnrdGMKP55ZZ_hxV0gU/edit#).

We are planning an initial release of ODK Central which implements this spec in the next few weeks. The release will be marked as experimental so that iteration on this spec can continue as needed.

2022-11-10 23:18 UTC, lognaturel commented
Marking as draft until I get a chance to actually run this (wrestling with Ruby).

2022-12-06 02:03 UTC, yanokwa requested changes
I did not confirm that this renders correctly.

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +The specifications is versioned using a `YYYY.NN.MM` scheme:
Drop the s from specification.

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +The `YYYY.MM` components of the version are only changed when a consumer built for an earlier version can no longer correctly use a form definition. For example, a version update will likely be made
Probably mean YYYY.NN not YYYY.MM

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +Implementers of the ODK XForms specification may choose to opt into this entities specification or ignore it entirely. For this reason, the entities layer is versioned separately from ODK XForms usin
"or ignore it entirely" doesn't add anything. If you are being verbose for clarity, maybe...

> Implementers of the ODK XForms specification may opt into this entities specification or ignore it entirely.

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +This specification uses the `http://www.opendatakit.org/xforms/entities` namespace for attributes added to nodes defined by the ODK XForms spec. The prefix commonly used for this namespace is `entiti
Drop "commonly". Either it's used or it's not.

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +Implementers of the ODK XForms specification may choose to opt into this entities specification or ignore it entirely. For this reason, the entities layer is versioned separately from ODK XForms usin
s/Implementers/consumers/ for consistency

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +- MUST have attribute `id` populated by a [RFC 4122 version 4 uuid](https://www.rfc-editor.org/rfc/rfc4122)
s/uuid/UUID/

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +**Entity actions**: Actions that can be taken on Entities (`create`)
actions should be Titlecase.

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +**Entity**: A uniquely-identified thing that a form is about.
s/thing/object/. I don't feel strongly about it.

Alternative...
> A uniquely-identified subject of a form.

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +**Immutable System Property**: An Entity Property that the system knows about and that can’t be changed (`dataset`, `id`)
Start parenthesis with e.g. Same for mutable system property and actions.

"That the system knows about" isn't clear and reads informal. Similar language for mutable property.
> An Entity Property that is reserved for system use only and whose value can’t be directly changed

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +    <model odk:xforms-version="1.0.0" entities:entities-version="2022.1.0">
I would expect version to have padding (`2022.01.00`)

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +Consumers MUST reject forms that specify a version code that is newer than what they can effectively process.
s/effectively/ because it's subjective. I'd drop it entirely or maybe "correctly"

Could make the sentence shorter.
> Consumers MUST reject forms with a version code

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +- `name` and `label` are reserved property names (for use when datasets are represented as itemset CSVs)
First time using itemset. Perhaps a link to the definition?

s/is used to declare/declares/

2022-12-06 02:03 UTC, yanokwa commented on _sections/120-entities.md
> +### Example entity-creating form
Example of an entity-creating form

2022-12-06 02:12 UTC, yanokwa commented on _sections/120-entities.md
> +- Property names follow the same rules as form field names (valid XML identifiers)
A link to the rules would be nice.

2022-12-06 02:13 UTC, yanokwa requested changes
Line 75 is the only potentially blocking change. The rest are for clarity.

2022-12-09 22:11 UTC, lognaturel commented on _sections/120-entities.md
> +This specification uses the `http://www.opendatakit.org/xforms/entities` namespace for attributes added to nodes defined by the ODK XForms spec. The prefix commonly used for this namespace is `entiti
The namespace prefix is arbitrary.

2022-12-09 22:16 UTC, lognaturel commented on _sections/120-entities.md
> +    <model odk:xforms-version="1.0.0" entities:entities-version="2022.1.0">
We already have several examples without padding so I'd rather be consistent. We also don't do 1.00.00.

2022-12-09 23:08 UTC, yanokwa approved these changes

2022-12-09 23:08 UTC, merged